#
# Awesome App Landing Page Config
#

# Be sure all REQUIRED fields are filled out!

#
# General App Info
#
app:
  name: EdenGreen # REQUIRED - Enter your app name
  developer: Daniel Dallos
  ios_id: 1422852547 # REQUIRED - 10 Digit Numeric App ID (lookup in iTunes Connect)
  android_id: com.danieldallos.myedenredbalancebe # Optional - Enter Android app id like: com.example.app

  icon: # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-icon-512.png
  # 512px or greater, square

  #favicon: # uncomment if uploading own favicon
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-favicon.png - can be .ico or .png
  # 16px or greater, square

  screenshot: images/screenshot_balance.png # Leave blank to auto-magically populate
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-screen-640x1136.png
  # 640x1136px

  #video: # uncomment if prefer to show a video preview in the screen instead of image
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-preview.mp4
  # 640x1136px

  #app_twitter: # uncomment if the app has a twitter account "@my-awesome-app"
  #creator_twitter: # uncomment if creator has a twitter account "@awesome-dev"
  #social_image: # uncomment and add an image - defaults to icon
  # This will show up when your url is shared on sites like facebook and twitter
  # To update use path relative to project root with no leading slash:
  # e.g. images/app-social_image.png
  # 512px or greater, square or width = 2X height
#
# Marketing
#
marketing_header: The EdenRed balance checker # Optional
marketing_desc: The best third-party EdenRed* balance checker application that keeps things nice and simple.<br/><br/><br/><font size=-1>*Current supported country is Belgium.<br/><br/><br/><strong>NOTE:</strong><br/>EdenGreen is an unofficial application for EdenRed card balances.<br/>The developer has no connection with Edenred Belgium.<br/>The application uses publicly available endpoints served by Edenred Belgium. Any change at the endpoint side can cause unexpected behavior in the application.</font>

#
# Social Links
#
# Includes an icon for each username you enter
#
social-links:
  github:
  facebook:
  twitter:
  pinterest:
  instagram:
  email: edengreen@danieldallos.com
  youtube: # channel/<your_long_string> or <user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

#
# Enable/Disable Features & Page Elements
#
enable:
  app_icon: true
  smart_app_banner: true

#
# Device
#
# Available devices:
# * iphone-se-silver-vertical
# * iphone-se-space-gray-vertical
# * ipod-touch-blue-vertical
#
device: iphone-se-space-gray-vertical # REQUIRED

#
# Theme Settings
#
background_color: "#000000" # Optional
background_image: /images/backgrounds/adam-kring-306084-unsplash.jpg # Optional - Use Relative path e.g. images/backgrounds/image.jpg
text_color: white # Optional
link_color: # Optional
social_link_color: white # Optional
download_button_background_color: "#40a33f" # Optional
download_button_text_color: white; # Optional

#
# Site Info
#
# If you want specific meta info for your <head></head> tags
#
title: EdenGreen, the EdenRed balance checker # Optional - Enter your site title
description: # Optional - Enter your site description

#
# Google Analytics
#
google_analytics: # Enter your tracking code (e.g. UA-2110908-2) to activate tracking

#
# iTunes Affiliate Program
#
# Sign up here: http://www.apple.com/itunes/affiliates/
#
# Disclaimer:
# This will default to using the author's affiliate token if left blank
#
itunes_affiliate_token: # Optional

#
# !! You don't need to change any of the configuration flags below !!
#

# The release of Awesome App Landing Page that you're using
version: v1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
